recipes = {'Test Recipe': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Blue',
                                             'optional': False},
											{'item': 'Brown',
                                             'optional': False},
                                            {'item': 'Indigo',
                                             'optional': False},
											{'item': 'Yellow',
                                             'optional': False},
                                            {'item': 'Lime',
                                             'optional': False},
											{'item': 'Orange',
                                             'optional': False}],
                           'steps': [{'name' : 'Insert Rod A into Slot B',
                                      'item' : ['Red', 'Blue', 'Brown', 'Indigo']},
                                     {'name' : 'The quick brown fox jumps over the lazy dog.',
                                      'item' : ['Yellow']},
									 {'name' : 'Test Step 3',
                                      'item' : ['Lime']},
                                     {'name' : 'Test Step 4 Test Step 4 Test Step 4 Test Step 4 Test Step 4 Test Step 4 Test Step 4',
                                      'item' : ['Orange']}]},

		   'Birdhouse': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False},
											{'item': 'Yellow',
                                             'optional': False},
											{'item': 'Yellow',
                                             'optional': False},
											{'item': 'Yellow',
                                             'optional': False},
											{'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red'],
                                      'targets': [{'item': 'Birdhouse Bottom',
                                                   'type': 'point',
                                                   'position': [0.22, 0.95]},
                                                  {'item': 'Birdhouse Bottom',
                                                   'type': 'point',
                                                   'position': [0.28, 0.95]},
                                                  {'item': 'Birdhouse Bottom',
                                                   'type': 'rectangle',
                                                   'position': [0.25, 1, 0.1, 0.1]}]},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow'],
                                      'targets': [{'item': 'Birdhouse Bottom',
                                                   'type': 'line',
                                                   'position': [-0.1, 1.1, 1.1, 1.1]}]}]},

		   'Flux Capacitor': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]},


		   'Water Filter': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]},

		   'Air Purifier': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]},

		   'Plank of wood with a nail through it': {'requirements': [{'item': 'Plank of Wood',
                                             'optional': False},
                                            {'item': 'Nail',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]}}

items = {'Red': {'color': [4, 98, 46]}, # Red
         'Orange': {'color': [9, 100, 58]}, # Orange
         'Yellow': {'color': [48, 53, 59]}, # Yellow
         'Lime': {'color': [157, 78, 33]}, # Lime
         'Green': {'color': [189, 96, 10]}, # Green
         'Blue': {'color': [210, 100, 31]}, # Blue
         'Indigo': {'color': [215, 100, 14]}, # Indigo
         'Brown': {'color': [16, 100, 9]}, # Brown
		 'Plank of Wood': {'color': [281, 100, 100]},
		 'Nail': {'color': [281, 100, 100]},
		 'test3': {'color': [281, 100, 100]},
		 'test4': {'color': [281, 100, 100]},
		 'test5': {'color': [281, 100, 100]},
		 'test6': {'color': [281, 100, 100]},
		 'test7': {'color': [281, 100, 100]},
		 'test8': {'color': [281, 100, 100]},
		 'test9': {'color': [281, 100, 100]},
		 'test10': {'color': [281, 100, 100]},
		 'test11': {'color': [281, 100, 100]},
		 'test12': {'color': [281, 100, 100]},
		 'test13': {'color': [281, 100, 100]},
		 'test14': {'color': [281, 100, 100]},
		 'test15': {'color': [281, 100, 100]},
		 'test16': {'color': [281, 100, 100]},
		 'test17': {'color': [281, 100, 100]}}
