recipes = {'Test Recipe': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Blue',
                                             'optional': False},
											{'item': 'Brown',
                                             'optional': False},
                                            {'item': 'Indigo',
                                             'optional': False},
											{'item': 'Yellow',
                                             'optional': False},
                                            {'item': 'Lime',
                                             'optional': False},
											{'item': 'Orange',
                                             'optional': False}],
                           'steps': [{'name' : 'Insert Rod A into Slot B',
                                      'item' : ['Red', 'Blue', 'Brown', 'Indigo']},
                                     {'name' : 'The quick brown fox jumps over the lazy dog.',
                                      'item' : ['Yellow']},
									 {'name' : 'Test Step 3',
                                      'item' : ['Lime']},
                                     {'name' : 'Test Step 4 Test Step 4 Test Step 4 Test Step 4 Test Step 4 Test Step 4 Test Step 4',
                                      'item' : ['Orange']}]},

		    'Birdhouse': {'requirements': [{'item': 'Birdhouse Base',
                                             'optional': False},
                                            {'item': 'Roof',
                                             'optional': False},
											{'item': 'Hinge',
                                             'optional': False},
											{'item': 'Screws',
                                             'optional': False},
											{'item': 'Mounting Bracket',
                                             'optional': False},
											{'item': 'Screwdriver',
                                             'optional': False}],
                           'steps': [{'name' : 'Place hinge with blue side out into the highlighted area. Align the two lower holes with the screw targets on the the birdhouse, and use the screwdriver with screws to attach hinge to the birdhouse.',
                                      'item' : ['Birdhouse Base, ', 'Hinge, ', 'Screws, ', 'Screwdriver'],
                                      'targets': [{'item': 'Birdhouse Base',
                                                   'type': 'point',
                                                   'position': [0.20, 0.975]},
                                                  {'item': 'Birdhouse Base',
                                                   'type': 'point',
                                                   'position': [0.25, 0.975]},
                                                  {'item': 'Birdhouse Base',
                                                   'type': 'rectangle',
                                                   'position': [0.225, 1, 0.2, 0.08]}]},
									 {'name' : 'Repeat Step 1 with second hinge.',
                                      'item' : ['Birdhouse Base, ', 'Hinge, ', 'Screws, ', 'Screwdriver'],
                                      'targets': [{'item': 'Birdhouse Base',
                                                   'type': 'point',
                                                   'position': [0.8, 0.025]},
                                                  {'item': 'Birdhouse Base',
                                                   'type': 'point',
                                                   'position': [0.75, 0.025]},
                                                  {'item': 'Birdhouse Base',
                                                   'type': 'rectangle',
                                                   'position': [0.775, 1, 0.2, 0.08]}]},
									 {'name' : 'Align roof screw targets with hinges. Use screwdriver with screws to attach roof to hinges.',
                                      'item' : ['Birdhouse Roof, ', 'Screws, ', 'Screwdriver' ],
                                      'targets': [{'item': 'Birdhouse Base',
                                                   'type': 'line',
                                                   'position': [-0.1, 1.1, 1.05, 1.05]}]},
									 {'name' : 'Align mounting bracket into the higlighted area. Use screwdriver to attach mounting bracket to the birdhouse.',
                                      'item' : ['Mounting Bracket, ' 'Screws, ' 'Screwdriver'],
                                      'targets': [{'item': 'Birdhouse Base',
                                                   'type': 'line',
                                                   'position': [-0.1, 1.1, 1.05, 1.05]}]}]},

		   'Flux Capacitor': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]},


		   'Water Filter': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]},

		   'Air Purifier': {'requirements': [{'item': 'Red',
                                             'optional': False},
                                            {'item': 'Yellow',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]},

		   'Plank of wood with a nail through it': {'requirements': [{'item': 'Plank of Wood',
                                             'optional': False},
                                            {'item': 'Nail',
                                             'optional': False}],
                           'steps': [{'name' : 'Test Step 1',
                                      'item' : ['Red']},
                                     {'name' : 'Test Step 2',
                                      'item' : ['Yellow']}]}}

items = {'Roof': {'color': [4, 98, 76]}, # Red
         'Orange': {'color': [9, 100, 58]}, # Orange
         'Screws': {'color': [55, 45, 82]}, # Yellow
         'Mounting Bracket': {'color': [155, 49, 33]}, # Lime
         'Green': {'color': [189, 96, 10]}, # Green
         'Hinge': {'color': [213, 78, 25]}, # Blue
         'Indigo': {'color': [215, 100, 14]}, # Indigo
         'Brown': {'color': [16, 100, 9]}, # Brown
         'White': {'color': [0, 0, 71]}, # White
         'Screwdriver': {'color': [75, 100, 10]}, # Black
         'Birdhouse Base': {'color': [20, 1, 84]}, # Painted white
		 'Plank of Wood': {'color': [281, 100, 100]},
		 'Nail': {'color': [281, 100, 100]},
		 'test3': {'color': [281, 100, 100]},
		 'test4': {'color': [281, 100, 100]},
		 'test5': {'color': [281, 100, 100]},
		 'test6': {'color': [281, 100, 100]},
		 'test7': {'color': [281, 100, 100]},
		 'test8': {'color': [281, 100, 100]},
		 'test9': {'color': [281, 100, 100]},
		 'test10': {'color': [281, 100, 100]},
		 'test11': {'color': [281, 100, 100]},
		 'test12': {'color': [281, 100, 100]},
		 'test13': {'color': [281, 100, 100]},
		 'test14': {'color': [281, 100, 100]},
		 'test15': {'color': [281, 100, 100]},
		 'test16': {'color': [281, 100, 100]},
		 'test17': {'color': [281, 100, 100]}}
